name: JMeter Performance Test

on:
  push:

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Download JMeter
        run: |
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz

      - name: Run JMeter
        run: |
          mkdir -p results
          mkdir -p reports

          ./apache-jmeter-5.6.3/bin/jmeter \
            -n \
            -t jmeter/Git.jmx \
            -l results/results.jtl \
            -e \
            -o reports/jmeter-report

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-performance-report
          path: |
            results/results.jtl
            reports/jmeter-report/